### ISSUE TITLE
allow the config file to define aliases

### ISSUE THREAD

**Issue by dhellmann** [dhellmann/demoshell#11]
Aliases would just expand to replace the shell command. That means parsing the command, which may make it harder to support different sub shells.

**Comment by shahbhavik01** [comment]
Hi, I am new to contributing to open source so please pardon my beginner mistakes. I created a fork of of this repo and have been able to provide aliases. Although I think I need a little help creating a config file. For now, I have just created a "demoshell.cfg" file but I'm not sure how you would like to create and store a config file on the system. Bash has ~/.bashrc but we need to create something similar for demoshell. Also, right now, it requires a strict format for alising like: ll = "ls -la" but I think I can make it more versatile. 

https://github.com/shahbhavik01/demoshell 

Please take a look at my branch. I really do love demoshell. Thank you.

**Comment by dhellmann** [comment]
Hi, and welcome!

The easiest way for me to review your code is if you create a "pull request", which is github's way of describing a set of changes you would like me to take from your repository and bring into this one.

To do that, navigate in your browser to your repository and then click the "Pull requests" tab. There should be a button on the top right labeled "New pull request" and clicking that will bring up a form to let you construct the pull request by selecting the branch on your side (it looks like you want "master") and on this side (you do definitely want master for that one).

For future changes, it will probably be easier for you to create separate branches in your repository (you can look at the "git branch" command for details, although I also like the simplicity of "git checkout -b"). Having separate branches will let you work on different parts of the project from the same git repository without mixing them up until they are merged into the main upstream repository.

I'm happy to help provide more guidance if any of that is still confusing, so please don't hesitate to ask questions here or by email (doug@doughellmann.com -- I get a lot of email so please refer to this discussion so I can connect your email with your GitHub ID and know who you are :-).

As far as implementation, I've started to like https://pypi.python.org/pypi/appdirs/1.4.3 for managing configuration file locations (you could use this for the history file patch, too). It has the benefit of putting all of the application configuration files in one place, without cluttering up the home directory.

I think an INI file format would work well for user-edited content, and the built-in configparser module is pretty easy to use. It looks like you've sort of reproduced the parser in the configparser module but in a less robust way, so maybe have a look at using that module directly to read and parse the files.

In addition to the code changes, it would be good if you could add some information to the readme file to explain which file to create/edit and what the format should be. An example would be very good.

We should also talk about what the shell should print out when an alias is entered. I could see us printing both the alias and the actual command run, for example. Or just the actual command. Let me know what you think.

**Comment by shahbhavik01** [comment]
Hi Doug,

I truly appreciate the detailed response and thank you for guiding me through this.

I will create separate branches for the specific patches. The appdirs module to create and manage config file in INI format really does seem versatile so I will use that. Also I'll use the built-in configparser module so that the code is more robust. Once I have it all, I'll make sure that the README is edited and add an example as well. 

I think you're right in that shell should print out when an alias is entered and print both the alias and the actual command run. I'll give it a shot. I'll get back to you once I have it down.

**Comment by dhellmann** [comment]
That sounds good. I'll watch for pull requests or comments on the tickets you choose to work on. Thanks for contributing to demoshell!

**Comment by shahbhavik01** [comment]
How do you think the user should add aliases? The bad way would be to hand edit the config files. I'm thinking we can build an "alias" command similar to bash but than I'm thinking it would conflict with the shell "alias" command.

**Comment by dhellmann** [comment]
I assumed we would ask people to edit the file directly for aliases they want on startup. Having an alias command built-in makes sense, too, though. If we did that, the startup file could just be a sequence of those commands that we execute.

**Comment by dhellmann** [comment]
This was resolved with #16
