### ISSUE TITLE
Cannot run with Ubuntu 18

### ISSUE THREAD

**Issue by namnh68** [dhellmann/demoshell#21]
Thanks for your tool, it's really helpful for me. But I cannot run this one on Ubuntu 18. It was sucessful when i install by command "pip3 install demoshell" [1].

When I run the command, here is the result [2]. Anw, it is good in Ubuntu16.

[1] https://prnt.sc/jd1hro 
[2] http://prntscr.com/jd1i1n

**Comment by salmanulfarzy** [comment]
Do you have the location of `demoshell` binary in your `$PATH` ?

**Comment by namnh68** [comment]
No, I dont'. This issue was fixed by cloning this repo and runing "sudo python setup.py install" manually. One more thing, it need to have __init__.py in the demoshell folder if using this way :)

**Comment by daikk115** [comment]
@namnh68 
have u try to find the directory of demoshell binary and append it for PATH?

**Comment by dhellmann** [comment]
Running pip as yourself isn't going to install to the same location that running it with sudo will. I suspect the first command installed demo shell to ~/.local/bin and that is not in your $PATH.
